version: '3.12'

services:
  web:
    build: .
    command: python manage.py runserver
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/foo
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo