# Generated by Django 5.1.2 on 2024-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('weekday', models.ManyToManyField(related_name='schedules', to='api.dayofweek')),
            ],
        ),
        migrations.CreateModel(
            name='Ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_name', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ManyToManyField(related_name='ids', to='api.schedule')),
            ],
        ),
    ]
